version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stackoverflow
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"
    networks:
      - appnet
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: dev
      DB_PASSWORD: devpass
      DB_PORT: 3306
      DB_NAME: stackoverflow
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: devpass
      JWT_SECRET: someKey
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
          - appnet
    volumes:
      - redis_data:/data

networks:
  appnet:

volumes:
  mysql_data:
  redis_data:
