definitions:
  models.Answer:
    properties:
      answer_id:
        type: integer
      comments:
        items:
          $ref: '#/definitions/models.Comment'
        type: array
      date:
        type: integer
      description:
        type: string
      question_id:
        description: Foreign key to Question
        type: integer
      user_id:
        type: integer
      votes:
        type: integer
    type: object
  models.Comment:
    properties:
      comment_id:
        type: integer
      date:
        type: integer
      description:
        type: string
      parent_id:
        type: integer
      parent_type:
        description: '"question" or "answer"'
        type: string
      user_id:
        type: integer
      votes:
        type: integer
    type: object
  models.Question:
    properties:
      date:
        type: integer
      description:
        type: string
      question_id:
        type: integer
      tags:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
      user_id:
        description: Foreign key to User
        type: integer
      votes:
        type: integer
    type: object
  models.Tag:
    properties:
      name:
        type: string
      questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
      tag_id:
        type: integer
    type: object
  models.User:
    properties:
      is_admin:
        type: boolean
      reputation:
        type: integer
      user_id:
        type: integer
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /answer/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Answer object
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/models.Answer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Answer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - answer
  /comment/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Comment object
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/models.Comment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Comment'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - comment
  /questions/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Question Data
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - questions
  /questions/all:
    get:
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - questions
  /questions/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: Question object
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - questions
  /questions/my/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - questions
  /questions/my/{user_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - questions
  /tag/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tag object
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/models.Tag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - tag
  /tag/questions/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - tag
  /user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tag object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - user
  /user/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Tag object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - user
swagger: "2.0"
