name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' 

    - name: Verify Go Version
      run: go version

    - name: Download Dependencies
      run: |
        go mod tidy
        go mod download

    - name: initialize swagger 
      run: swag init

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./...

    - name: Debug If Fails
      if: failure()
      run: cat go.mod && cat go.sum
